name: CICD on GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch: # allows manual trigger of the workflow in GitHub console

jobs:
  pre-build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: PrepareKeychain
      run: ci_actions/01_keychain.sh
    - name: PrepareAmplify
      run: ci_actions/02_amplify.sh

  build:

    needs: pre-build

    runs-on: self-hosted

    steps:
    - name: Build
      run: ci_actions/03_build.sh

  test:

    needs: build
    
    runs-on: self-hosted

    steps:

    - name: LocalTest
      run: ci_actions/04_local_tests.sh

  deploy:

    needs: test
    
    runs-on: self-hosted

    steps:

    - name: Deploy to TestFlight
      run: ci_actions/06_deploy_testflight.sh

  cleanup:

    needs: deploy
    
    runs-on: self-hosted

    steps:

    - name: cleanup
      run: ci_actions/07_cleanup.sh
